# ProManage Test Environment Configuration
# Temporary configuration to bypass database connection issues

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  # Disable Flyway for test
  flyway:
    enabled: false

  # Disable Redis for test
  redis:
    enabled: false

  # Disable JPA for test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# Disable MyBatis Plus for test
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      logic-delete-field: deleted
      logic-delete-value: true
      logic-not-delete-value: false
      id-type: auto

# Logging Configuration for test
logging:
  level:
    root: INFO
    com.promanage: DEBUG
    org.springframework: WARN