# ProManage Development Environment Configuration

spring:
  datasource:
    druid:
      url: jdbc:postgresql://192.168.18.7:5432/promanage
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver

      # Connection Pool Configuration
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

      # Connection Test Configuration
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1
      validation-query-timeout: 3000

      # Connection Timeout Configuration
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 600000

      # Monitoring and Statistics
      filters: stat,slf4j
      wall:
        enabled: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: ${DRUID_USERNAME:admin}
        login-password: ${DRUID_PASSWORD:admin}
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  # Redis Configuration
  redis:
    host: 192.168.18.7
    port: 6379
    password:
    database: 0
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
      shutdown-timeout: 100ms

  # Flyway Database Migration Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true
    table: flyway_schema_history
    encoding: UTF-8
    placeholder-replacement: true
    placeholders:
      database: promanage

  # Mail Configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    default-encoding: UTF-8

  # RabbitMQ Configuration (Optional)
  # rabbitmq:
  #   host: localhost
  #   port: 5672
  #   username: guest
  #   password: guest
  #   virtual-host: /

# MyBatis Plus Configuration
mybatis-plus:
  configuration:
    # Development mode - show SQL logs
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    auto-mapping-behavior: partial
    default-executor-type: reuse
    default-statement-timeout: 25000

  global-config:
    banner: false
    db-config:
      # Logical Delete Configuration
      logic-delete-field: deleted
      logic-delete-value: true
      logic-not-delete-value: false
      # ID Generation Strategy
      id-type: auto

  # Mapper XML Location
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.promanage.service.entity

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:VGVjaG5pY2FsU2VjcmV0S2V5UGxlYXNlQ2hhbmdlTWV0b09uZVBsZWFzZUxvbmdlclNlY3JldEtleUZvckRldk9ubHk=}  # Default for dev environment, overwrite in production
  expiration: ${JWT_EXPIRATION:3600000}  # 1 hour (reduced from 24 hours for better security)
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}  # 24 hours (reduced from 7 days)
  issuer: ProManage
  header: Authorization
  token-prefix: Bearer

# User Configuration
user:
  default-role-id: 2  # 默认角色ID (普通用户)
  password-min-length: 8
  password-max-length: 32
  username-min-length: 4
  username-max-length: 20

# Elasticsearch Configuration (Optional)
# elasticsearch:
#   host: localhost
#   port: 9200
#   scheme: http
#   username: elastic
#   password: elastic

# MinIO Configuration (Optional)
# minio:
#   endpoint: http://localhost:9000
#   access-key: minioadmin
#   secret-key: minioadmin
#   bucket-name: promanage

# Logging Configuration
logging:
  level:
    root: INFO
    com.promanage: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.baomidou.mybatisplus: DEBUG
    com.zaxxer.hikari: DEBUG
  file:
    name: logs/promanage-dev.log
    max-size: 100MB
    max-history: 30
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%t] %-40.40logger{39} : %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%t] %-40.40logger{39} : %m%n"

# Management Endpoints Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    info:
      enabled: true
  health:
    redis:
      enabled: true
    db:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
      environment: dev