# ProManage Application Configuration
# Base configuration file for all environments

spring:
  application:
    name: promanage

  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
      file-size-threshold: 10MB

  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
  group-configs:
    - group: auth
      paths-to-match: /api/auth/**
      display-name: Authentication APIs
    - group: user
      paths-to-match: /api/users/**
      display-name: User Management APIs
    - group: project
      paths-to-match: /api/projects/**
      display-name: Project Management APIs
    - group: document
      paths-to-match: /api/documents/**
      display-name: Document Management APIs
    - group: system
      paths-to-match: /api/roles/**, /api/permissions/**
      display-name: System Management APIs

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  error:
    include-message: always
    include-binding-errors: always